# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T11:45:12+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel, confloat, conint, constr


class AccessDeniedException(RootModel[Any]):
    root: Any


class CPU(RootModel[confloat(ge=0.0)]):
    root: confloat(ge=0.0)


class CancelDeploymentRequest(BaseModel):
    pass


class ClientTokenString(
    RootModel[constr(pattern=r'^[a-zA-Z0-9-]+$', min_length=1, max_length=64)]
):
    root: constr(pattern=r'^[a-zA-Z0-9-]+$', min_length=1, max_length=64)


class CloudComponentState(Enum):
    REQUESTED = 'REQUESTED'
    INITIATED = 'INITIATED'
    DEPLOYABLE = 'DEPLOYABLE'
    FAILED = 'FAILED'
    DEPRECATED = 'DEPRECATED'


class ComponentARN(
    RootModel[
        constr(pattern=r'arn:[^:]*:greengrass:[^:]*:(aws|[0-9]+):components:[^:]+')
    ]
):
    root: constr(pattern=r'arn:[^:]*:greengrass:[^:]*:(aws|[0-9]+):components:[^:]+')


class ComponentConfigurationPath(RootModel[constr(min_length=0, max_length=256)]):
    root: constr(min_length=0, max_length=256)


class ComponentConfigurationPathList(RootModel[List[ComponentConfigurationPath]]):
    root: List[ComponentConfigurationPath]


class ComponentConfigurationString(
    RootModel[constr(min_length=1, max_length=10485760)]
):
    root: constr(min_length=1, max_length=10485760)


class ComponentConfigurationUpdate(BaseModel):
    merge: Optional[ComponentConfigurationString] = None
    reset: Optional[ComponentConfigurationPathList] = None


class ComponentDependencyType(Enum):
    HARD = 'HARD'
    SOFT = 'SOFT'


class ComponentNameString(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class ComponentVersionARN(
    RootModel[
        constr(
            pattern=r'arn:[^:]*:greengrass:[^:]*:(aws|[0-9]+):components:[^:]+:versions:[^:]+'
        )
    ]
):
    root: constr(
        pattern=r'arn:[^:]*:greengrass:[^:]*:(aws|[0-9]+):components:[^:]+:versions:[^:]+'
    )


class ComponentVersionString(RootModel[constr(min_length=1, max_length=64)]):
    root: constr(min_length=1, max_length=64)


class ComponentVisibilityScope(Enum):
    PRIVATE = 'PRIVATE'
    PUBLIC = 'PUBLIC'


class ConflictException(RootModel[Any]):
    root: Any


class CoreDeviceArchitectureString(RootModel[constr(min_length=1, max_length=255)]):
    root: constr(min_length=1, max_length=255)


class CoreDevicePlatformString(RootModel[constr(min_length=1, max_length=255)]):
    root: constr(min_length=1, max_length=255)


class CoreDeviceStatus(Enum):
    HEALTHY = 'HEALTHY'
    UNHEALTHY = 'UNHEALTHY'


class CoreDeviceThingName(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class DefaultMaxResults(RootModel[conint(ge=1, le=100)]):
    root: conint(ge=1, le=100)


class DeleteComponentRequest(BaseModel):
    pass


class DeleteCoreDeviceRequest(BaseModel):
    pass


class DeleteDeploymentRequest(BaseModel):
    pass


class DeploymentComponentUpdatePolicyAction(Enum):
    NOTIFY_COMPONENTS = 'NOTIFY_COMPONENTS'
    SKIP_NOTIFY_COMPONENTS = 'SKIP_NOTIFY_COMPONENTS'


class DeploymentFailureHandlingPolicy(Enum):
    ROLLBACK = 'ROLLBACK'
    DO_NOTHING = 'DO_NOTHING'


class DeploymentHistoryFilter(Enum):
    ALL = 'ALL'
    LATEST_ONLY = 'LATEST_ONLY'


class DeploymentID(RootModel[str]):
    root: str


class DeploymentName(RootModel[str]):
    root: str


class DeploymentNameString(RootModel[constr(min_length=1, max_length=256)]):
    root: constr(min_length=1, max_length=256)


class DeploymentStatus(Enum):
    ACTIVE = 'ACTIVE'
    COMPLETED = 'COMPLETED'
    CANCELED = 'CANCELED'
    FAILED = 'FAILED'
    INACTIVE = 'INACTIVE'


class DescribeComponentRequest(BaseModel):
    pass


class Description(RootModel[constr(min_length=1, max_length=500)]):
    root: constr(min_length=1, max_length=500)


class DescriptionString(RootModel[str]):
    root: str


class DisassociateServiceRoleFromAccountRequest(BaseModel):
    pass


class EffectiveDeploymentErrorCode(RootModel[constr(min_length=1, max_length=255)]):
    root: constr(min_length=1, max_length=255)


class EffectiveDeploymentErrorStack(RootModel[List[EffectiveDeploymentErrorCode]]):
    root: List[EffectiveDeploymentErrorCode]


class EffectiveDeploymentErrorType(RootModel[constr(min_length=1, max_length=255)]):
    root: constr(min_length=1, max_length=255)


class EffectiveDeploymentErrorTypeList(RootModel[List[EffectiveDeploymentErrorType]]):
    root: List[EffectiveDeploymentErrorType]


class EffectiveDeploymentExecutionStatus(Enum):
    IN_PROGRESS = 'IN_PROGRESS'
    QUEUED = 'QUEUED'
    FAILED = 'FAILED'
    COMPLETED = 'COMPLETED'
    TIMED_OUT = 'TIMED_OUT'
    CANCELED = 'CANCELED'
    REJECTED = 'REJECTED'
    SUCCEEDED = 'SUCCEEDED'


class EffectiveDeploymentStatusDetails(BaseModel):
    errorStack: Optional[EffectiveDeploymentErrorStack] = None
    errorTypes: Optional[EffectiveDeploymentErrorTypeList] = None


class FileSystemPath(RootModel[str]):
    root: str


class GGCVersion(RootModel[constr(min_length=1, max_length=255)]):
    root: constr(min_length=1, max_length=255)


class GenericV2ARN(
    RootModel[
        constr(
            pattern=r'arn:[^:]*:greengrass:[^:]*:(aws|[0-9]+):(components|deployments|coreDevices):.*'
        )
    ]
):
    root: constr(
        pattern=r'arn:[^:]*:greengrass:[^:]*:(aws|[0-9]+):(components|deployments|coreDevices):.*'
    )


class GetComponentRequest(BaseModel):
    pass


class GetComponentVersionArtifactRequest(BaseModel):
    pass


class GetConnectivityInfoRequest(BaseModel):
    pass


class GetCoreDeviceRequest(BaseModel):
    pass


class GetDeploymentRequest(BaseModel):
    pass


class GetServiceRoleForAccountRequest(BaseModel):
    pass


class InstalledComponentLifecycleState(Enum):
    NEW = 'NEW'
    INSTALLED = 'INSTALLED'
    STARTING = 'STARTING'
    RUNNING = 'RUNNING'
    STOPPING = 'STOPPING'
    ERRORED = 'ERRORED'
    BROKEN = 'BROKEN'
    FINISHED = 'FINISHED'


class InstalledComponentLifecycleStatusCode(
    RootModel[constr(min_length=1, max_length=255)]
):
    root: constr(min_length=1, max_length=255)


class InstalledComponentLifecycleStatusCodeList(
    RootModel[List[InstalledComponentLifecycleStatusCode]]
):
    root: List[InstalledComponentLifecycleStatusCode]


class InstalledComponentTopologyFilter(Enum):
    ALL = 'ALL'
    ROOT = 'ROOT'


class InternalServerException(RootModel[Any]):
    root: Any


class IoTJobARN(RootModel[constr(pattern=r'arn:[^:]*:iot:[^:]+:[0-9]+:job/.+')]):
    root: constr(pattern=r'arn:[^:]*:iot:[^:]+:[0-9]+:job/.+')


class IoTJobAbortAction(Enum):
    CANCEL = 'CANCEL'


class IoTJobAbortThresholdPercentage(RootModel[confloat(le=100.0)]):
    root: confloat(le=100.0)


class IoTJobExecutionFailureType(Enum):
    FAILED = 'FAILED'
    REJECTED = 'REJECTED'
    TIMED_OUT = 'TIMED_OUT'
    ALL = 'ALL'


class IoTJobId(RootModel[constr(min_length=1, max_length=255)]):
    root: constr(min_length=1, max_length=255)


class IoTJobInProgressTimeoutInMinutes(RootModel[int]):
    root: int


class IoTJobMaxExecutionsPerMin(RootModel[conint(ge=1, le=1000)]):
    root: conint(ge=1, le=1000)


class IoTJobMinimumNumberOfExecutedThings(RootModel[conint(ge=1)]):
    root: conint(ge=1)


class IoTJobNumberOfThings(RootModel[conint(ge=1)]):
    root: conint(ge=1)


class IoTJobRateIncreaseCriteria(BaseModel):
    numberOfNotifiedThings: Optional[IoTJobNumberOfThings] = None
    numberOfSucceededThings: Optional[IoTJobNumberOfThings] = None


class IoTJobRolloutBaseRatePerMinute(RootModel[conint(ge=1, le=1000)]):
    root: conint(ge=1, le=1000)


class IoTJobRolloutIncrementFactor(RootModel[confloat(ge=1.0, le=5.0)]):
    root: confloat(ge=1.0, le=5.0)


class IoTJobTimeoutConfig(BaseModel):
    inProgressTimeoutInMinutes: Optional[IoTJobInProgressTimeoutInMinutes] = None


class IoTThingName(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class IsLatestForTarget(RootModel[bool]):
    root: bool


class IsRoot(RootModel[bool]):
    root: bool


class LambdaEventSourceType(Enum):
    PUB_SUB = 'PUB_SUB'
    IOT_CORE = 'IOT_CORE'


class LambdaExecArg(RootModel[str]):
    root: str


class LambdaExecArgsList(RootModel[List[LambdaExecArg]]):
    root: List[LambdaExecArg]


class LambdaFilesystemPermission(Enum):
    ro = 'ro'
    rw = 'rw'


class LambdaInputPayloadEncodingType(Enum):
    json = 'json'
    binary = 'binary'


class LambdaIsolationMode(Enum):
    GreengrassContainer = 'GreengrassContainer'
    NoContainer = 'NoContainer'


class LifecycleStateDetails(RootModel[constr(min_length=1, max_length=1000)]):
    root: constr(min_length=1, max_length=1000)


class ListClientDevicesAssociatedWithCoreDeviceRequest(BaseModel):
    pass


class ListComponentVersionsRequest(BaseModel):
    pass


class ListComponentsRequest(BaseModel):
    pass


class ListCoreDevicesRequest(BaseModel):
    pass


class ListDeploymentsRequest(BaseModel):
    pass


class ListEffectiveDeploymentsRequest(BaseModel):
    pass


class ListInstalledComponentsRequest(BaseModel):
    pass


class ListTagsForResourceRequest(BaseModel):
    pass


class Memory(RootModel[conint(ge=0, le=9223372036854772000)]):
    root: conint(ge=0, le=9223372036854772000)


class NextTokenString(RootModel[str]):
    root: str


class NonEmptyString(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class NullableString(RootModel[str]):
    root: str


class OptionalBoolean(RootModel[bool]):
    root: bool


class OptionalInteger(RootModel[int]):
    root: int


class PlatformAttributesMap(RootModel[Optional[Dict[str, NonEmptyString]]]):
    root: Optional[Dict[str, NonEmptyString]] = None


class PortNumberInt(RootModel[conint(ge=0, le=65535)]):
    root: conint(ge=0, le=65535)


class PublisherString(RootModel[str]):
    root: str


class Reason(RootModel[str]):
    root: str


class RecipeBlob(RootModel[str]):
    root: str


class RecipeOutputFormat(Enum):
    JSON = 'JSON'
    YAML = 'YAML'


class RequestAlreadyInProgressException(RootModel[Any]):
    root: Any


class ResourceNotFoundException(RootModel[Any]):
    root: Any


class ServiceQuotaExceededException(RootModel[Any]):
    root: Any


class String(RootModel[str]):
    root: str


class StringMap(RootModel[Optional[Dict[str, NonEmptyString]]]):
    root: Optional[Dict[str, NonEmptyString]] = None


class SystemResourceLimits(BaseModel):
    cpus: Optional[CPU] = None
    memory: Optional[Memory] = None


class TagKey(RootModel[constr(min_length=1, max_length=128)]):
    root: constr(min_length=1, max_length=128)


class TagKeyList(RootModel[List[TagKey]]):
    root: List[TagKey] = Field(..., max_length=200, min_length=1)


class TagResourceResponse(BaseModel):
    pass


class TagValue(RootModel[constr(max_length=256)]):
    root: constr(max_length=256)


class TargetARN(
    RootModel[constr(pattern=r'arn:[^:]*:iot:[^:]*:[0-9]+:(thing|thinggroup)/.+')]
):
    root: constr(pattern=r'arn:[^:]*:iot:[^:]*:[0-9]+:(thing|thinggroup)/.+')


class ThingGroupARN(
    RootModel[constr(pattern=r'arn:[^:]*:iot:[^:]*:[0-9]+:thinggroup/.+')]
):
    root: constr(pattern=r'arn:[^:]*:iot:[^:]*:[0-9]+:thinggroup/.+')


class ThrottlingException(RootModel[Any]):
    root: Any


class Timestamp(RootModel[datetime]):
    root: datetime


class TopicString(RootModel[str]):
    root: str


class UntagResourceRequest(BaseModel):
    pass


class UntagResourceResponse(BaseModel):
    pass


class UpdateConnectivityInfoResponse(BaseModel):
    message: Optional[String] = None
    version: Optional[String] = None


class ValidationException(RootModel[Any]):
    root: Any


class VendorGuidance(Enum):
    ACTIVE = 'ACTIVE'
    DISCONTINUED = 'DISCONTINUED'
    DELETED = 'DELETED'


class GreengrassServicerolePutRequest(BaseModel):
    RoleArn: str = Field(
        ...,
        description='The Amazon Resource Name (ARN) of the service role to associate with IoT Greengrass for your Amazon Web Services account in this Amazon Web Services Region.',
    )


class Scope(Enum):
    PRIVATE = 'PRIVATE'
    PUBLIC = 'PUBLIC'


class Status(Enum):
    HEALTHY = 'HEALTHY'
    UNHEALTHY = 'UNHEALTHY'


class TopologyFilter(Enum):
    ALL = 'ALL'
    ROOT = 'ROOT'


class HistoryFilter(Enum):
    ALL = 'ALL'
    LATEST_ONLY = 'LATEST_ONLY'


class Platform(BaseModel):
    attributes: Optional[PlatformAttributesMap] = None
    name: Optional[NonEmptyString] = None


class TagsResourceArnPostRequest(BaseModel):
    tags: Dict[str, TagValue] = Field(
        ...,
        description='A list of key-value pairs that contain metadata for the resource. For more information, see <a href="https://docs.aws.amazon.com/greengrass/v2/developerguide/tag-resources.html">Tag your resources</a> in the <i>IoT Greengrass V2 Developer Guide</i>.',
    )


class TagKeys(RootModel[List[TagKey]]):
    root: List[TagKey] = Field(..., max_length=200, min_length=1)


class AssociateClientDeviceWithCoreDeviceEntry(BaseModel):
    thingName: IoTThingName


class AssociateClientDeviceWithCoreDeviceEntryList(
    RootModel[List[AssociateClientDeviceWithCoreDeviceEntry]]
):
    root: List[AssociateClientDeviceWithCoreDeviceEntry] = Field(
        ..., max_length=100, min_length=1
    )


class AssociateClientDeviceWithCoreDeviceErrorEntry(BaseModel):
    code: Optional[NonEmptyString] = None
    message: Optional[NonEmptyString] = None
    thingName: Optional[IoTThingName] = None


class AssociateClientDeviceWithCoreDeviceErrorList(
    RootModel[List[AssociateClientDeviceWithCoreDeviceErrorEntry]]
):
    root: List[AssociateClientDeviceWithCoreDeviceErrorEntry] = Field(
        ..., max_length=100
    )


class AssociateServiceRoleToAccountRequest(BaseModel):
    roleArn: String


class AssociateServiceRoleToAccountResponse(BaseModel):
    associatedAt: Optional[String] = None


class AssociatedClientDevice(BaseModel):
    associationTimestamp: Optional[Timestamp] = None
    thingName: Optional[IoTThingName] = None


class AssociatedClientDeviceList(RootModel[List[AssociatedClientDevice]]):
    root: List[AssociatedClientDevice] = Field(..., max_length=100, min_length=1)


class BatchAssociateClientDeviceWithCoreDeviceRequest(BaseModel):
    entries: Optional[AssociateClientDeviceWithCoreDeviceEntryList] = None


class BatchAssociateClientDeviceWithCoreDeviceResponse(BaseModel):
    errorEntries: Optional[AssociateClientDeviceWithCoreDeviceErrorList] = None


class CancelDeploymentResponse(BaseModel):
    message: Optional[NonEmptyString] = None


class CloudComponentStatus(BaseModel):
    componentState: Optional[CloudComponentState] = None
    errors: Optional[StringMap] = None
    message: Optional[NonEmptyString] = None
    vendorGuidance: Optional[VendorGuidance] = None
    vendorGuidanceMessage: Optional[NonEmptyString] = None


class ComponentDependencyRequirement(BaseModel):
    dependencyType: Optional[ComponentDependencyType] = None
    versionRequirement: Optional[NonEmptyString] = None


class ComponentPlatform(BaseModel):
    attributes: Optional[PlatformAttributesMap] = None
    name: Optional[NonEmptyString] = None


class ComponentPlatformList(RootModel[List[ComponentPlatform]]):
    root: List[ComponentPlatform]


class ComponentRunWith(BaseModel):
    posixUser: Optional[NonEmptyString] = None
    systemResourceLimits: Optional[SystemResourceLimits] = None
    windowsUser: Optional[NonEmptyString] = None


class ComponentVersionListItem(BaseModel):
    arn: Optional[NonEmptyString] = None
    componentName: Optional[ComponentNameString] = None
    componentVersion: Optional[ComponentVersionString] = None


class ComponentVersionRequirementMap(RootModel[Optional[Dict[str, NonEmptyString]]]):
    root: Optional[Dict[str, NonEmptyString]] = None


class ConnectivityInfo(BaseModel):
    hostAddress: Optional[String] = None
    id: Optional[String] = None
    metadata: Optional[String] = None
    portNumber: Optional[PortNumberInt] = None


class CoreDevice(BaseModel):
    coreDeviceThingName: Optional[CoreDeviceThingName] = None
    lastStatusUpdateTimestamp: Optional[Timestamp] = None
    status: Optional[CoreDeviceStatus] = None


class CoreDevicesList(RootModel[List[CoreDevice]]):
    root: List[CoreDevice]


class CreateComponentVersionResponse(BaseModel):
    arn: Optional[ComponentVersionARN] = None
    componentName: ComponentNameString
    componentVersion: ComponentVersionString
    creationTimestamp: Timestamp
    status: CloudComponentStatus


class CreateDeploymentResponse(BaseModel):
    deploymentId: Optional[NonEmptyString] = None
    iotJobArn: Optional[IoTJobARN] = None
    iotJobId: Optional[NonEmptyString] = None


class Deployment(BaseModel):
    creationTimestamp: Optional[Timestamp] = None
    deploymentId: Optional[NonEmptyString] = None
    deploymentName: Optional[NonEmptyString] = None
    deploymentStatus: Optional[DeploymentStatus] = None
    isLatestForTarget: Optional[IsLatestForTarget] = None
    parentTargetArn: Optional[ThingGroupARN] = None
    revisionId: Optional[NonEmptyString] = None
    targetArn: Optional[TargetARN] = None


class DeploymentComponentUpdatePolicy(BaseModel):
    action: Optional[DeploymentComponentUpdatePolicyAction] = None
    timeoutInSeconds: Optional[OptionalInteger] = None


class DeploymentConfigurationValidationPolicy(BaseModel):
    timeoutInSeconds: Optional[OptionalInteger] = None


class DeploymentList(RootModel[List[Deployment]]):
    root: List[Deployment]


class DeploymentPolicies(BaseModel):
    componentUpdatePolicy: Optional[DeploymentComponentUpdatePolicy] = None
    configurationValidationPolicy: Optional[DeploymentConfigurationValidationPolicy] = (
        None
    )
    failureHandlingPolicy: Optional[DeploymentFailureHandlingPolicy] = None


class DisassociateClientDeviceFromCoreDeviceEntry(BaseModel):
    thingName: IoTThingName


class DisassociateClientDeviceFromCoreDeviceEntryList(
    RootModel[List[DisassociateClientDeviceFromCoreDeviceEntry]]
):
    root: List[DisassociateClientDeviceFromCoreDeviceEntry] = Field(
        ..., max_length=100, min_length=1
    )


class DisassociateClientDeviceFromCoreDeviceErrorEntry(BaseModel):
    code: Optional[NonEmptyString] = None
    message: Optional[NonEmptyString] = None
    thingName: Optional[IoTThingName] = None


class DisassociateClientDeviceFromCoreDeviceErrorList(
    RootModel[List[DisassociateClientDeviceFromCoreDeviceErrorEntry]]
):
    root: List[DisassociateClientDeviceFromCoreDeviceErrorEntry] = Field(
        ..., max_length=100
    )


class DisassociateServiceRoleFromAccountResponse(BaseModel):
    disassociatedAt: Optional[String] = None


class EffectiveDeployment(BaseModel):
    coreDeviceExecutionStatus: EffectiveDeploymentExecutionStatus
    creationTimestamp: Timestamp
    deploymentId: DeploymentID
    deploymentName: DeploymentName
    description: Optional[Description] = None
    iotJobArn: Optional[IoTJobARN] = None
    iotJobId: Optional[IoTJobId] = None
    modifiedTimestamp: Timestamp
    reason: Optional[Reason] = None
    statusDetails: Optional[EffectiveDeploymentStatusDetails] = None
    targetArn: TargetARN


class EffectiveDeploymentsList(RootModel[List[EffectiveDeployment]]):
    root: List[EffectiveDeployment]


class GetComponentVersionArtifactResponse(BaseModel):
    preSignedUrl: NonEmptyString


class GetServiceRoleForAccountResponse(BaseModel):
    associatedAt: Optional[String] = None
    roleArn: Optional[String] = None


class InstalledComponent(BaseModel):
    componentName: Optional[ComponentNameString] = None
    componentVersion: Optional[ComponentVersionString] = None
    isRoot: Optional[IsRoot] = None
    lastInstallationSource: Optional[NonEmptyString] = None
    lastReportedTimestamp: Optional[Timestamp] = None
    lastStatusChangeTimestamp: Optional[Timestamp] = None
    lifecycleState: Optional[InstalledComponentLifecycleState] = None
    lifecycleStateDetails: Optional[LifecycleStateDetails] = None
    lifecycleStatusCodes: Optional[InstalledComponentLifecycleStatusCodeList] = None


class InstalledComponentList(RootModel[List[InstalledComponent]]):
    root: List[InstalledComponent]


class IoTJobAbortCriteria(BaseModel):
    action: IoTJobAbortAction
    failureType: IoTJobExecutionFailureType
    minNumberOfExecutedThings: IoTJobMinimumNumberOfExecutedThings
    thresholdPercentage: IoTJobAbortThresholdPercentage


class IoTJobAbortCriteriaList(RootModel[List[IoTJobAbortCriteria]]):
    root: List[IoTJobAbortCriteria] = Field(..., min_length=1)


class IoTJobExponentialRolloutRate(BaseModel):
    baseRatePerMinute: IoTJobRolloutBaseRatePerMinute
    incrementFactor: IoTJobRolloutIncrementFactor
    rateIncreaseCriteria: IoTJobRateIncreaseCriteria


class LambdaDeviceMount(BaseModel):
    addGroupOwner: Optional[OptionalBoolean] = None
    path: FileSystemPath
    permission: Optional[LambdaFilesystemPermission] = None


class LambdaEnvironmentVariables(RootModel[Optional[Dict[str, String]]]):
    root: Optional[Dict[str, String]] = None


class LambdaEventSource(BaseModel):
    topic: TopicString
    type: LambdaEventSourceType


class LambdaEventSourceList(RootModel[List[LambdaEventSource]]):
    root: List[LambdaEventSource]


class LambdaVolumeMount(BaseModel):
    addGroupOwner: Optional[OptionalBoolean] = None
    destinationPath: FileSystemPath
    permission: Optional[LambdaFilesystemPermission] = None
    sourcePath: FileSystemPath


class ListClientDevicesAssociatedWithCoreDeviceResponse(BaseModel):
    associatedClientDevices: Optional[AssociatedClientDeviceList] = None
    nextToken: Optional[NextTokenString] = None


class ListCoreDevicesResponse(BaseModel):
    coreDevices: Optional[CoreDevicesList] = None
    nextToken: Optional[NextTokenString] = None


class ListDeploymentsResponse(BaseModel):
    deployments: Optional[DeploymentList] = None
    nextToken: Optional[NextTokenString] = None


class ListEffectiveDeploymentsResponse(BaseModel):
    effectiveDeployments: Optional[EffectiveDeploymentsList] = None
    nextToken: Optional[NextTokenString] = None


class ListInstalledComponentsResponse(BaseModel):
    installedComponents: Optional[InstalledComponentList] = None
    nextToken: Optional[NextTokenString] = None


class ResolvedComponentVersion(BaseModel):
    arn: Optional[ComponentVersionARN] = None
    componentName: Optional[ComponentNameString] = None
    componentVersion: Optional[ComponentVersionString] = None
    message: Optional[NonEmptyString] = None
    recipe: Optional[RecipeBlob] = None
    vendorGuidance: Optional[VendorGuidance] = None


class ResolvedComponentVersionsList(RootModel[List[ResolvedComponentVersion]]):
    root: List[ResolvedComponentVersion]


class TagMap(RootModel[Optional[Dict[str, TagValue]]]):
    root: Optional[Dict[str, TagValue]] = None


class TagResourceRequest(BaseModel):
    tags: TagMap


class ConnectivityInfoList(RootModel[List[ConnectivityInfo]]):
    root: List[ConnectivityInfo]


class GreengrassThingsThingNameConnectivityInfoPutRequest(BaseModel):
    ConnectivityInfo_1: List[ConnectivityInfo] = Field(
        ...,
        alias='ConnectivityInfo',
        description='The connectivity information for the core device.',
    )


class GreengrassV2CoreDevicesCoreDeviceThingNameAssociateClientDevicesPostRequest(
    BaseModel
):
    entries: Optional[List[AssociateClientDeviceWithCoreDeviceEntry]] = Field(
        None,
        description='The list of client devices to associate.',
        max_length=100,
        min_length=1,
    )


class GreengrassV2CoreDevicesCoreDeviceThingNameDisassociateClientDevicesPostRequest(
    BaseModel
):
    entries: Optional[List[DisassociateClientDeviceFromCoreDeviceEntry]] = Field(
        None,
        description='The list of client devices to disassociate.',
        max_length=100,
        min_length=1,
    )


class BatchDisassociateClientDeviceFromCoreDeviceRequest(BaseModel):
    entries: Optional[DisassociateClientDeviceFromCoreDeviceEntryList] = None


class BatchDisassociateClientDeviceFromCoreDeviceResponse(BaseModel):
    errorEntries: Optional[DisassociateClientDeviceFromCoreDeviceErrorList] = None


class ComponentCandidate(BaseModel):
    componentName: Optional[ComponentNameString] = None
    componentVersion: Optional[ComponentVersionString] = None
    versionRequirements: Optional[ComponentVersionRequirementMap] = None


class ComponentCandidateList(RootModel[List[ComponentCandidate]]):
    root: List[ComponentCandidate]


class ComponentDependencyMap(
    RootModel[Optional[Dict[str, ComponentDependencyRequirement]]]
):
    root: Optional[Dict[str, ComponentDependencyRequirement]] = None


class ComponentDeploymentSpecification(BaseModel):
    componentVersion: Optional[ComponentVersionString] = None
    configurationUpdate: Optional[ComponentConfigurationUpdate] = None
    runWith: Optional[ComponentRunWith] = None


class ComponentDeploymentSpecifications(
    RootModel[Optional[Dict[str, ComponentDeploymentSpecification]]]
):
    root: Optional[Dict[str, ComponentDeploymentSpecification]] = None


class ComponentLatestVersion(BaseModel):
    arn: Optional[ComponentVersionARN] = None
    componentVersion: Optional[ComponentVersionString] = None
    creationTimestamp: Optional[Timestamp] = None
    description: Optional[NonEmptyString] = None
    platforms: Optional[ComponentPlatformList] = None
    publisher: Optional[NonEmptyString] = None


class ComponentVersionList(RootModel[List[ComponentVersionListItem]]):
    root: List[ComponentVersionListItem]


class DescribeComponentResponse(BaseModel):
    arn: Optional[ComponentVersionARN] = None
    componentName: Optional[ComponentNameString] = None
    componentVersion: Optional[ComponentVersionString] = None
    creationTimestamp: Optional[Timestamp] = None
    description: Optional[DescriptionString] = None
    platforms: Optional[ComponentPlatformList] = None
    publisher: Optional[PublisherString] = None
    status: Optional[CloudComponentStatus] = None
    tags: Optional[TagMap] = None


class GetComponentResponse(BaseModel):
    recipe: RecipeBlob
    recipeOutputFormat: RecipeOutputFormat
    tags: Optional[TagMap] = None


class GetConnectivityInfoResponse(BaseModel):
    connectivityInfo: Optional[ConnectivityInfoList] = None
    message: Optional[String] = None


class GetCoreDeviceResponse(BaseModel):
    architecture: Optional[CoreDeviceArchitectureString] = None
    coreDeviceThingName: Optional[CoreDeviceThingName] = None
    coreVersion: Optional[GGCVersion] = None
    lastStatusUpdateTimestamp: Optional[Timestamp] = None
    platform: Optional[CoreDevicePlatformString] = None
    status: Optional[CoreDeviceStatus] = None
    tags: Optional[TagMap] = None


class IoTJobAbortConfig(BaseModel):
    criteriaList: IoTJobAbortCriteriaList


class IoTJobExecutionsRolloutConfig(BaseModel):
    exponentialRate: Optional[IoTJobExponentialRolloutRate] = None
    maximumPerMinute: Optional[IoTJobMaxExecutionsPerMin] = None


class LambdaDeviceList(RootModel[List[LambdaDeviceMount]]):
    root: List[LambdaDeviceMount]


class LambdaVolumeList(RootModel[List[LambdaVolumeMount]]):
    root: List[LambdaVolumeMount]


class ListComponentVersionsResponse(BaseModel):
    componentVersions: Optional[ComponentVersionList] = None
    nextToken: Optional[NextTokenString] = None


class ListTagsForResourceResponse(BaseModel):
    tags: Optional[TagMap] = None


class ResolveComponentCandidatesRequest(BaseModel):
    componentCandidates: Optional[ComponentCandidateList] = None
    platform: Optional[ComponentPlatform] = None


class ResolveComponentCandidatesResponse(BaseModel):
    resolvedComponentVersions: Optional[ResolvedComponentVersionsList] = None


class UpdateConnectivityInfoRequest(BaseModel):
    connectivityInfo: ConnectivityInfoList


class IotJobConfiguration(BaseModel):
    abortConfig: Optional[IoTJobAbortConfig] = None
    jobExecutionsRolloutConfig: Optional[IoTJobExecutionsRolloutConfig] = None
    timeoutConfig: Optional[IoTJobTimeoutConfig] = None


class GreengrassV2DeploymentsPostRequest(BaseModel):
    clientToken: Optional[
        constr(pattern=r'^[a-zA-Z0-9-]+$', min_length=1, max_length=64)
    ] = Field(
        None,
        description='A unique, case-sensitive identifier that you can provide to ensure that the request is idempotent. Idempotency means that the request is successfully processed only once, even if you send the request multiple times. When a request succeeds, and you specify the same client token for subsequent successful requests, the IoT Greengrass V2 service returns the successful response that it caches from the previous request. IoT Greengrass V2 caches successful responses for idempotent requests for up to 8 hours.',
    )
    components: Optional[Dict[str, ComponentDeploymentSpecification]] = Field(
        None,
        description="The components to deploy. This is a dictionary, where each key is the name of a component, and each key's value is the version and configuration to deploy for that component.",
    )
    deploymentName: Optional[constr(min_length=1, max_length=256)] = Field(
        None, description='The name of the deployment.'
    )
    deploymentPolicies: Optional[DeploymentPolicies] = Field(
        None,
        description='Contains information about policies that define how a deployment updates components and handles failure.',
    )
    iotJobConfiguration: Optional[IotJobConfiguration] = Field(
        None, description='Contains information about an IoT job configuration.'
    )
    parentTargetArn: Optional[
        constr(pattern=r'arn:[^:]*:iot:[^:]*:[0-9]+:thinggroup/.+')
    ] = Field(
        None,
        description='The parent deployment\'s target <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">ARN</a> within a subdeployment.',
    )
    tags: Optional[Dict[str, TagValue]] = Field(
        None,
        description='A list of key-value pairs that contain metadata for the resource. For more information, see <a href="https://docs.aws.amazon.com/greengrass/v2/developerguide/tag-resources.html">Tag your resources</a> in the <i>IoT Greengrass V2 Developer Guide</i>.',
    )
    targetArn: constr(pattern=r'arn:[^:]*:iot:[^:]*:[0-9]+:(thing|thinggroup)/.+') = (
        Field(
            ...,
            description='The <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">ARN</a> of the target IoT thing or thing group. When creating a subdeployment, the targetARN can only be a thing group.',
        )
    )


class GreengrassV2ResolveComponentCandidatesPostRequest(BaseModel):
    componentCandidates: Optional[List[ComponentCandidate]] = Field(
        None, description='The list of components to resolve.'
    )
    platform: Optional[Platform] = Field(
        None,
        description='Contains information about a platform that a component supports.',
    )


class Component(BaseModel):
    arn: Optional[ComponentARN] = None
    componentName: Optional[ComponentNameString] = None
    latestVersion: Optional[ComponentLatestVersion] = None


class ComponentList(RootModel[List[Component]]):
    root: List[Component]


class DeploymentIoTJobConfiguration(BaseModel):
    abortConfig: Optional[IoTJobAbortConfig] = None
    jobExecutionsRolloutConfig: Optional[IoTJobExecutionsRolloutConfig] = None
    timeoutConfig: Optional[IoTJobTimeoutConfig] = None


class GetDeploymentResponse(BaseModel):
    components: Optional[ComponentDeploymentSpecifications] = None
    creationTimestamp: Optional[Timestamp] = None
    deploymentId: Optional[NonEmptyString] = None
    deploymentName: Optional[NullableString] = None
    deploymentPolicies: Optional[DeploymentPolicies] = None
    deploymentStatus: Optional[DeploymentStatus] = None
    iotJobArn: Optional[IoTJobARN] = None
    iotJobConfiguration: Optional[DeploymentIoTJobConfiguration] = None
    iotJobId: Optional[NullableString] = None
    isLatestForTarget: Optional[IsLatestForTarget] = None
    parentTargetArn: Optional[ThingGroupARN] = None
    revisionId: Optional[NonEmptyString] = None
    tags: Optional[TagMap] = None
    targetArn: Optional[TargetARN] = None


class LambdaContainerParams(BaseModel):
    devices: Optional[LambdaDeviceList] = None
    memorySizeInKB: Optional[OptionalInteger] = None
    mountROSysfs: Optional[OptionalBoolean] = None
    volumes: Optional[LambdaVolumeList] = None


class LambdaLinuxProcessParams(BaseModel):
    containerParams: Optional[LambdaContainerParams] = None
    isolationMode: Optional[LambdaIsolationMode] = None


class ListComponentsResponse(BaseModel):
    components: Optional[ComponentList] = None
    nextToken: Optional[NextTokenString] = None


class CreateDeploymentRequest(BaseModel):
    clientToken: Optional[ClientTokenString] = None
    components: Optional[ComponentDeploymentSpecifications] = None
    deploymentName: Optional[DeploymentNameString] = None
    deploymentPolicies: Optional[DeploymentPolicies] = None
    iotJobConfiguration: Optional[DeploymentIoTJobConfiguration] = None
    parentTargetArn: Optional[ThingGroupARN] = None
    tags: Optional[TagMap] = None
    targetArn: TargetARN


class LambdaExecutionParameters(BaseModel):
    environmentVariables: Optional[LambdaEnvironmentVariables] = None
    eventSources: Optional[LambdaEventSourceList] = None
    execArgs: Optional[LambdaExecArgsList] = None
    inputPayloadEncodingType: Optional[LambdaInputPayloadEncodingType] = None
    linuxProcessParams: Optional[LambdaLinuxProcessParams] = None
    maxIdleTimeInSeconds: Optional[OptionalInteger] = None
    maxInstancesCount: Optional[OptionalInteger] = None
    maxQueueSize: Optional[OptionalInteger] = None
    pinned: Optional[OptionalBoolean] = None
    statusTimeoutInSeconds: Optional[OptionalInteger] = None
    timeoutInSeconds: Optional[OptionalInteger] = None


class LambdaFunctionRecipeSource(BaseModel):
    componentDependencies: Optional[ComponentDependencyMap] = None
    componentLambdaParameters: Optional[LambdaExecutionParameters] = None
    componentName: Optional[ComponentNameString] = None
    componentPlatforms: Optional[ComponentPlatformList] = None
    componentVersion: Optional[ComponentVersionString] = None
    lambdaArn: NonEmptyString


class LambdaFunction(BaseModel):
    componentDependencies: Optional[ComponentDependencyMap] = None
    componentLambdaParameters: Optional[LambdaExecutionParameters] = None
    componentName: Optional[ComponentNameString] = None
    componentPlatforms: Optional[ComponentPlatformList] = None
    componentVersion: Optional[ComponentVersionString] = None
    lambdaArn: Optional[NonEmptyString] = None


class GreengrassV2CreateComponentVersionPostRequest(BaseModel):
    clientToken: Optional[
        constr(pattern=r'^[a-zA-Z0-9-]+$', min_length=1, max_length=64)
    ] = Field(
        None,
        description='A unique, case-sensitive identifier that you can provide to ensure that the request is idempotent. Idempotency means that the request is successfully processed only once, even if you send the request multiple times. When a request succeeds, and you specify the same client token for subsequent successful requests, the IoT Greengrass V2 service returns the successful response that it caches from the previous request. IoT Greengrass V2 caches successful responses for idempotent requests for up to 8 hours.',
    )
    inlineRecipe: Optional[str] = Field(
        None,
        description="<p>The recipe to use to create the component. The recipe defines the component's metadata, parameters, dependencies, lifecycle, artifacts, and platform compatibility.</p> <p>You must specify either <code>inlineRecipe</code> or <code>lambdaFunction</code>.</p>",
    )
    lambdaFunction: Optional[LambdaFunction] = Field(
        None,
        description='Contains information about an Lambda function to import to create a component.',
    )
    tags: Optional[Dict[str, TagValue]] = Field(
        None,
        description='A list of key-value pairs that contain metadata for the resource. For more information, see <a href="https://docs.aws.amazon.com/greengrass/v2/developerguide/tag-resources.html">Tag your resources</a> in the <i>IoT Greengrass V2 Developer Guide</i>.',
    )


class CreateComponentVersionRequest(BaseModel):
    clientToken: Optional[ClientTokenString] = None
    inlineRecipe: Optional[RecipeBlob] = None
    lambdaFunction: Optional[LambdaFunctionRecipeSource] = None
    tags: Optional[TagMap] = None
